Feature/composer update tests integration
BurdaMagazinOrg/thunder-infrastructure pull request #16
Opened 2017-04-19 10:35 UTC by mtodor

- added composer update testing on Cron run
- updated drush to ^8.1.10

2017-04-19 15:57 UTC, dbosen requested changes

2017-04-19 15:57 UTC, dbosen commented on ci/travis/scripts/test-composer-update.sh
> +composer global require "burdamagazinorg/update-tester:@dev"
Tag an alpha release for update tester and use a cleaner require statement

2017-04-20 09:30 UTC, mtodor commented
PR is ready now.

2017-04-20 09:41 UTC, dbosen approved these changes

2017-04-20 09:41 UTC, merged